version: '3'
services:  
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - {{ APPDATA_DIR }}/data:/mosquitto/data
      - {{ APPDATA_DIR }}/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
