version: '3'

volumes:
  readsbpb_rrd:
  readsbpb_autogain:

services:
  readsb:
    image: mikenye/readsb-protobuf:latest
    tty: true
    container_name: readsb
    restart: always
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - {{ WEB_PORT }}:8080
      - {{ SBS1_OUT_PORT }}:30003
      - {{ BEAST_OUT_PORT }}:30005
    environment:
      - TZ="{{ TIME_ZONE }}"
      - READSB_DCFILTER=true
      - READSB_DEVICE_TYPE=rtlsdr
      - READSB_FIX=true
      - READSB_GAIN=autogain
      - READSB_LAT="{{ LOCATION_LAT }}"
      - READSB_LON="{{ LOCATION_LNG }}"
      - READSB_MODEAC=true
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      - READSB_NET_ENABLE=true
    volumes:
      - readsbpb_rrd:/run/collectd
      - readsbpb_autogain:/run/autogain

{% if FLIGHTAWARE_FEEDER_ID %}
  piaware:
    image: mikenye/piaware:latest
    tty: true
    container_name: piaware
    restart: always
    environment:
      - BEASTHOST=readsb
      - TZ="{{ TIME_ZONE }}"
      - LAT="{{ LOCATION_LAT }}"
      - LONG="{{ LOCATION_LNG }}"
      - FEEDER_ID="{{ FLIGHTAWARE_FEEDER_ID }}"
{% endif %}

{% if FLIGHTRADAR24_KEY %}
  fr24feed:
    image: mikenye/fr24feed:latest
    tty: true
    container_name: fr24feed
    restart: always
    ports:
      - 8754
    environment:
      - BEASTHOST=readsb
      - FR24KEY="{{ FLIGHTRADAR24_KEY }}"
{% endif %}

{% if ADSBEXCHANGE_KEY %}
  adsbexchange:
    image: mikenye/adsbexchange
    tty: true
    container_name: adsbx
    restart: always
    environment:
      - BEASTHOST=readsb
      - TZ={{ TIME_ZONE }}
      - LAT={{ LOCATION_LAT }}
      - LONG={{ LOCATION_LNG }}
      - ALT={{ ALTITUDE_METERS }}m
      - SITENAME={{ ADSBEXCHANGE_SITE_NAME }}
      - UUID={{ ADSBEXCHANGE_KEY }}
{% endif %}
