version: '3'
services:
  autoheal:
    image: "hgogonis/autoheal-armhf"
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
