version: '3'
services:
  homeassistant:
    image: "homeassistant/home-assistant:stable"
    restart: always
    network_mode: host
    volumes:
      - {{ APPDATA_DIR }}/config:/config
    environment:
      - TZ={{ TIME_ZONE }}

{% if DEVICE_NAME %}
  zwavejs:
    image: kpine/zwave-js-server:latest
    restart: always
    devices:
      - {{ DEVICE_NAME }}:{{ DEVICE_NAME }}
    volumes:
      - {{ APPDATA_DIR }}/cache:/cache
    environment:
      - USB_PATH={{ DEVICE_NAME }}
      - S0_LEGACY_KEY={{ S0_LEGACY_KEY }}
    ports:
      - {{ OZW_PORT }}:3000
{% endif %}
