version: '3'
services:
  homeassistant:
    image: "homeassistant/home-assistant:stable"
    restart: always
    volumes:
      - {{ APPDATA_DIR }}/config:/config
    environment:
      - TZ={{ TIME_ZONE }}
{% if DEVICE_NAME %}
    devices:
      - {{ DEVICE_NAME }}:{{ DEVICE_NAME }}
{% endif %}
