version: '3'
services:  
  telegraf:
    container_name: telegraf
    image: telegraf:latest
    restart: unless-stopped
    volumes:
      - {{ APPDATA_DIR }}/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
